# Generated by Django 3.0.5 on 2021-01-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_title_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='рейтинг'),
        ),
    ]
